In [1]:
import numpy as np

In [7]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [8]:
arr = np.array(my_list)
print type(arr)
arr

<type 'numpy.ndarray'>


array([1, 2, 3])

In [9]:
np.arange(0,20,5) #similar to range python command

array([ 0,  5, 10, 15])

In [10]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [11]:
np.zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
np.ones(8)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [14]:
np.ones((2,8))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [15]:
np.linspace(0,30,3) #returns 3 points

array([  0.,  15.,  30.])

In [18]:
np.random.randint(0,20) #return a randomm int

5

In [19]:
np.random.randint(0,20,(3,3)) #return an array with random int in it

array([[ 5,  5, 10],
       [ 1, 12, 11],
       [19, 11,  6]])

In [23]:
np.random.seed(101)
arr = np.random.randint(0,100,10) #seed should be in the same cell with the second random commands
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [25]:
arr.max()

95

In [26]:
arr.min()

9

In [27]:
arr.mean()

60.799999999999997

In [28]:
arr.argmax()

0

In [29]:
arr.argmin()

7

In [30]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [31]:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [32]:
mat = np.arange(0,100).reshape(10,10)

In [33]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [36]:
mat[0,9]

9

In [37]:
mat[:,0] #only first col

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [39]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [40]:
mat[0:3,0:3] #not includes 3, goes from 0 to 2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [43]:
my_filter = mat > 10 # This is called Masking, a very useful feature in numpy!

In [45]:
mat[my_filter]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
       62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
       79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
       96, 97, 98, 99])

In [ ]:
# That's pretty much it!