In [2]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[59, 44],
       [ 2, 97],
       [13, 86],
       [85, 19],
       [38, 29],
       [ 0, 55],
       [54,  3],
       [26, 73],
       [21,  0],
       [75, 17]])

In [5]:
scaler = MinMaxScaler()
type(scaler)

sklearn.preprocessing.data.MinMaxScaler

In [6]:
scaler.fit(data)

/home/javidi/.local/lib/python2.7/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scaler.transform(data)

array([[ 0.69411765,  0.45360825],
       [ 0.02352941,  1.        ],
       [ 0.15294118,  0.88659794],
       [ 1.        ,  0.19587629],
       [ 0.44705882,  0.29896907],
       [ 0.        ,  0.56701031],
       [ 0.63529412,  0.03092784],
       [ 0.30588235,  0.75257732],
       [ 0.24705882,  0.        ],
       [ 0.88235294,  0.17525773]])

In [9]:
scaler.fit_transform(data)

array([[ 0.69411765,  0.45360825],
       [ 0.02352941,  1.        ],
       [ 0.15294118,  0.88659794],
       [ 1.        ,  0.19587629],
       [ 0.44705882,  0.29896907],
       [ 0.        ,  0.56701031],
       [ 0.63529412,  0.03092784],
       [ 0.30588235,  0.75257732],
       [ 0.24705882,  0.        ],
       [ 0.88235294,  0.17525773]])

In [10]:
import pandas as pd
mydata = np.random.randint(0,101,(50,4))

In [11]:
mydata

array([[ 73,  58,  69,   9],
       [ 52, 100,   3,  87],
       [ 72,  82,  72,  37],
       [ 45,  58,  72,  13],
       [ 48,  54,  61,  69],
       [ 53,   7,  19,  46],
       [ 75,  33,  16,  83],
       [ 46,  11,  69,  70],
       [ 98,  44,  85,  50],
       [ 21,  66,  52,  36],
       [  0,   4,  50,  45],
       [ 60,  66,  58,  43],
       [ 91,  53,  23,  22],
       [ 32,   5,  19,  92],
       [ 47,  37,  56,  79],
       [ 34,  46,  14,  79],
       [ 69,  26,  74,  16],
       [ 95,  84,  66,  46],
       [100,  21,  43,  83],
       [ 52,  82,  70,  23],
       [ 21,   5,  63,  38],
       [ 80,  14,  11,  13],
       [ 10,  24,   6,  68],
       [ 96,  53,  48,  81],
       [ 24,  85,  27,  85],
       [ 83,  92,  27,  15],
       [ 66,  74,  70,  92],
       [ 88,  54,  44,  96],
       [ 42,  59,   5,  75],
       [ 10,  87,  25,  82],
       [ 36,  23,  60,  80],
       [ 74,   4,  98,  46],
       [ 90,  75,  55,  89],
       [100,  76,  98,  17],
       [ 31,  

In [18]:
df = pd.DataFrame(data=mydata, columns=['f1','f2','f3', 'label'])

In [19]:
df

f1   f2   f3  label
0    73   58   69      9
1    52  100    3     87
2    72   82   72     37
3    45   58   72     13
4    48   54   61     69
5    53    7   19     46
6    75   33   16     83
7    46   11   69     70
8    98   44   85     50
9    21   66   52     36
10    0    4   50     45
11   60   66   58     43
12   91   53   23     22
13   32    5   19     92
14   47   37   56     79
15   34   46   14     79
16   69   26   74     16
17   95   84   66     46
18  100   21   43     83
19   52   82   70     23
20   21    5   63     38
21   80   14   11     13
22   10   24    6     68
23   96   53   48     81
24   24   85   27     85
25   83   92   27     15
26   66   74   70     92
27   88   54   44     96
28   42   59    5     75
29   10   87   25     82
30   36   23   60     80
31   74    4   98     46
32   90   75   55     89
33  100   76   98     17
34   31   32   39     85
35    1   32   63     22
36   73   19   69     36
37   69   29   88     91
38   44   71   13     42
39   54   44    0     44
40   94   35   55     65
41   90   74   92    100
42   80   89   73     35
43   97   22   69     70
44   31   63   86     65
45   13   58   17      3
46   39   99   29     63
47   21   33   50      0
48   65   56    0     44
49   63   46  100     10

In [25]:
X = df[['f1','f2','f3']]

In [23]:
y = df['label']

In [24]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [28]:
X_train.shape

(33, 3)

In [29]:
X_test.shape

(17, 3)